### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Antidotec** [yongqyu/STRNN#11]
Sorry to bother you.
When I tried to use the processed dataset to train,it runned very well,but when I was trying to use the 'preprocess.py' to cut the dataset 'Gowalla_totalCheckins.txt', an error has occurred, “too many indices for array“ ,line 100,finally i have fixed it ,in line 100 and 102 you need to delete '[0]' .

data = ','.join(str(e.data.cpu().numpy()) for e in locs[w_cap:idx])+"\t"
f.write(data)
data = str(locs[idx].data.cpu().numpy())+"\n"
f.write(data)

**Comment by yongqyu** [comment]
Thank you for your attention.
Now I do not have an environment where I can modify and run this code.
It's hard to reflect your advice right now, but I'll fix it as soon as possible.
Thank you again.

**Comment by jsjs2009** [comment]
Sorry to bother you.
Your experiment's results is much lower than the results from the referenced article.
I want to know whether there some other tricks in the model training process.

**Comment by yongqyu** [comment]
There are many questions about this.
But I couldn't figure out the exact reason, and I'm left with this repository because of my limitations.
I guess it's a matter of embedding time and space.
It's been a while since I've done this research, so it's hard to give a detailed answer.

Thank you.

**Comment by jsjs2009** [comment]
Thank you for your .

发送自 Windows 10 版邮件应用

发件人: yongqyu
发送时间: 2019年11月11日 9:52
收件人: yongqyu/STRNN
抄送: jsjs2009; Comment
主题: Re: [yongqyu/STRNN] dataset (#11)

There are many questions about this.
But I couldn't figure out the exact reason, and I'm left with this repository because of my limitations.
I guess it's a matter of embedding time and space.
It's been a while since I've done this research, so it's hard to give a detailed answer.
Thank you.
