### ISSUE TITLE
Question about the Gowalla dataset

### ISSUE THREAD

**Issue by SY1706203** [yongqyu/STRNN#7]
Hi Yongqyu,

Thank you for re-implementing ST-RNN. I am quite interested in it. However, I have some questions about the Gowalla dataset in the file prepro_train_50.txt. The code says that time_window=360 minutes, but in the first column of the file prepro_train_50.txt have some time interval greater than 360 minutes:
1
82.25	0.331054	133	132
1297.62	0.109035	132	131
382.5,321.375,32.5625	0.0926226,0.0924566,0.00229809	131,130,129	128
3783.62	9.29145	128	6
1942.94	0.00119504	6	1
3338.06	25.7679	1	127
2272.69	25.7676	127	35

By the way, what is your opinion about this ?

Thanks,
Liu zhuang

**Comment by yongqyu** [comment]
Thank you for your interest.

I think this result seems odd. But it's been a long time since I've written this code, and I can not afford to focus on it right now.

The relevant hyperparameter is located at 23:28 in preprocess.py.
I'm sorry I can not give you a concrete solution.
I will check once more if I have time.

Thank you.
